### ISSUE TITLE
Margin Shortfall Surplus screen has corrupted Search function

### ISSUE THREAD

**Issue by desezde** [Deutsche-Boerse-Risk/DAVe#20]
Comparing with "Position Reports" screen "Search" field on "Margin Shortfall Surplus" 
1) screen  is working only for 3 character, in case you will write 4+ characters - there is an empty list.
2)  filter is from some reason not working for strings like  "EUR",  "CB" 

Test data on https://172.23.39.44:9000/#/marginShortfallSurplusLatest

**Comment by scholzj** [comment]
@desezde I think that this is because of the data ... CB is basically in every record because of **CB**KFR. The same EU, which is the clearing currency and as such it is in every record. What 4+ characters did you used to get empty list?

**Comment by desezde** [comment]
With this informations I see that  point 1) is because its not searching base on  "Pool Tp." column (and another columns with numbers... some other screens are supporting searching base on columns with numbers... and does not support another columns with string...)

I see the problem now. There is a lot of screens with different columns ant only a few of them are linked to the search function...

**Comment by scholzj** [comment]
Correct, it is searching only through the so called "functonal key". That normally includes all columns expect from the numbers.

That is probably not completely correct. I think that not searching through the number is fine. But there is exactly one case where a text field is not part of the functional key and that is the Pool type. The pool type should be probably searchable as well.

**Comment by scholzj** [comment]
Additionally, the functional key contains the fields concatenated with `-`. As a result, a search for something like -1 or -A might return surprising results, because it is found int he key but not necessarily in the human readable text.

This might be applied in general, since even fields invisible in the UI are searched (e.g. the clearer).

**Comment by scholzj** [comment]
@desezde I updated the filter. It should now filter all values in the table (some values are not visible), not only the values which are included in the functional key. It also filters the numbers (but not as formatted in the table, but without the thousand separators).  This is probably the best I can do right now. Please have a look and let me know whether it is now OK or not.

**Comment by desezde** [comment]
@scholzj OK for me. At least that not visible columns can be visible in exported .csv file e.g. column with the clearer
