### ISSUE TITLE
The config file should store only the ERS broker hostname, without the protocol

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe#23]
The ERS broker configuration is currently confusing. It doesn't use URL - it has separate hostname and port. Yet, the hostname is sexpected to contain the `tcp://` from the URL. We should decide and use only one - either URL or separate fields without URL segmenets. 

The second case seems to be preferable. The hostname should be stored only as hostname and the `tcp://` should be added inside DAVe.

**Comment by zerola** [comment]
Protocol is specified in the code and not in the config.
