### ISSUE TITLE
Give the user an option to select which columns should be drawn into the chart

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe#28]
Right now, the charts are often useless because they mix very different values. As a result, the chart shows 5 almost straight lines. The user should have the possibility to select the columns which will be drawn - that way the user can control the chart "quality".

**Comment by Eddman** [comment]
Google Charts support a DataTable and DataView as a data source for all charts. DataView is a wrapper around DataTable and allows developers to create views on top of the data. It has methods:

| Method       | Description |
| ------------- |--------------|
| hideColumns(columnIndexes) | Hides the specified columns from the current view. columnIndexes is an array of numbers representing the indexes of the columns to hide. These indexes are the index numbers in the underlying table/view. The numbers in columnIndexes do not have to be in order (that is, [3,4,1] is fine). The remaining columns retain their index order when you iterate through them. Entering an index number for a column already hidden is not an error, but entering an index that does not exist in the underlying table/view will throw an error. To unhide columns, call setColumns(). Example: If you have a table with 10 columns, and you call setColumns([2,7,1,7,9]), and then hideColumns([7,9]), the columns in the view will then be [2,1].|
| hideRows(min, max) | Hides all rows with indexes that lie between min and max (inclusive) from the current view. This is a convenience syntax for hideRows(rowIndexes) above. For example, hideRows(5, 10) is equivalent to hideRows([5, 6, 7, 8, 9, 10]). |
| hideRows(rowIndexes) |	 Hides the specified rows from the current view. rowIndexes is an array of numbers representing the indexes of the rows to hide. These indexes are the index numbers in the underlying table/view. The numbers in rowIndexes do not have to be in order (that is, [3,4,1] is fine). The remaining rows retain their index order. Entering an index number for a row already hidden is not an error, but entering an index that does not exist in the underlying table/view will throw an error. To unhide rows, call setRows(). Example: If you have a table with 10 rows, and you call setRows([2,7,1,7,9]), and then hideRows([7,9]), the rows in the view will then be [2,1]. |

Using the first one we can hide a specific line in the chart.

**Comment by scholzj** [comment]
@Eddman Can we add the Total Margin chart to the Margin Components History chart?

**Comment by Eddman** [comment]
@scholzj Please be more specific. What do you want to add?

**Comment by scholzj** [comment]
A new line in the chart for the "Total Margin" column, which already exists in the Margin Compoennts History view but is not in the chart.

**Comment by Eddman** [comment]
Sure. Please open an issue in [Deutsche-Boerse-Risk/DAVe-UI](/Deutsche-Boerse-Risk/DAVe-UI). I'll do that next week or if I have a few minutes to spare this week. Will see.

**Comment by scholzj** [comment]
This has been fixed in the UI repo and can be close, or?
