### ISSUE TITLE
Change sorting for the tables from purely alphabetical to sorting by importance

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe#40]
Currently, most tables are sorted by the functional key by default. However it might make more sense to sort the tables by how significant they are. To do so, use following as the main sorting key:
- [x] Total Margin for the overview on dashboard and for latest MC table
- [x] Position VaR for the Positions table
- [x] Stop level utilization on Risk Limits
- [x] ??? on TMR table
- [x] ??? on MSS table

**Comment by markadir** [comment]
Total Margin for the TMR table and by Shortfall with lowest value first.

**Comment by scholzj** [comment]
The sorting is now implemented in all tables.
