### ISSUE TITLE
Bubble chart tooltip

### ISSUE THREAD

**Issue by zerola** [Deutsche-Boerse-Risk/DAVe#44]
Tooltips in bubble chart currently show numbers as X and Y coordinates - instead of the displayed values (since the values have to be integers but we want to display some meaningful strings). Could the X and Y attributes in tooltips be changed to the displayed strings?

**Comment by zerola** [comment]
Google charts support configuration of tooltips for various graphs, unfortunately Bubble chart is not among [them](https://developers.google.com/chart/interactive/docs/customizing_tooltip_content#supported-charts). Let's postpone this issue and decide whether we want to use another chart library or "hack" the tooltip somehow with JS.

**Comment by Eddman** [comment]
You may close it :+1:

**Comment by zerola** [comment]
Implemented by Adam's last PR. Closing.
