### ISSUE TITLE
Update to Vert.x 3.4.0

### ISSUE THREAD

**Issue by zerola** [Deutsche-Boerse-Risk/DAVe#57]

**Comment by halajos** [comment]
Implemented by c08a52f27ca112b2a37981496c2b8fd12e1718a9

**Comment by halajos** [comment]
Implemented by [Update to Vert.x 3.4.0](https://github.com/Deutsche-Boerse-Risk/DAVe/commit/c08a52f27ca112b2a37981496c2b8fd12e1718a9)
