### ISSUE TITLE
Add possibility to limit the memory consumption

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe#65]
There should be possibility to control the memory consupmption ot the application (-Xmx etc.). What about add support for environment variable JAVA_OPTIONS into the startup scripts? Such variable can be flexibly set for example when running the application in containers on Kubernetes and can contain things like "-Xmx512m". The default value can be also added to the Dockerfile. What do you think?

The same should be done also in the loader.

**Comment by zerola** [comment]
Implemented
